routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Dashboard

Route::get('/', function () {
    return redirect('/admin');
});

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {

        //Ralationship işlemleri için test controller
        Route::get('/test', 'OrganizationController@index');

        Route::get('/', function () {
            return view('admin.default.index');
        })->middleware('auth')->name('default.index');

        //user
        Route::resource('user', 'UserController')->middleware('auth');

        //corporation
        Route::resource('corporation', 'CorporationController')->middleware('auth');
        Route::resource('report', 'ReportController')->middleware('auth');
        Route::get('export', 'ReportController@export');

        Route::get('/ajax/geographic-boundaries', 'AjaxController@getGeographicBoundriesByParentId')->name('ajax.geographic-boundaries');
        Route::get('/ajax/organizations', 'AjaxController@getOrganizationsByParentId')->name('ajax.organizations');
        Route::get('/ajax/corporations', 'AjaxController@getCorporationByOrganizationId')->name('ajax.corporations');
        Route::get('/ajax/roles', 'AjaxController@getRolesByOrganizationId')->name('ajax.roles');
        Route::post('/ajax/enqueue-sms', 'AjaxController@enqueueSms')->name('ajax.enqueue.sms');

        //product type
        Route::resource('product', 'ProductTypeController')->middleware('auth');

        //payment
        Route::resource('payment', 'PaymentController')->middleware('auth');
        Route::put('/payment/cancel/{id}', 'PaymentController@cancelPayment')->name('payment.cancel');

        // Role
        Route::resource('role', 'RoleController')->middleware('auth');

        // Permission
        Route::resource('permission', 'PermissionController')->middleware('auth');

    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-sms', 'SmsController@enqueue');


Route::get('/payment/success', 'PaymentController@success')->name('payments.success');
Route::get('/payment/fail', 'PaymentController@fail')->name('payments.fail');
Route::get('/payment/{code}', 'PaymentController@payment')->name('payments.index');


// finansbank
Route::get('/bank/finansbank', 'BankController@finansbank')->name('bank.finansbank');
Route::any('/bank/finansbank/return', 'BankController@finansbankReturn')->name('bank.finansbankReturn');

//  ziraatbankasi
Route::get('/bank/ziraatbankasi', 'BankController@ziraatbankasi')->name('bank.ziraatbankasi');
Route::any('/bank/ziraatbankasi/return', 'BankController@ziraatbankasiReturn')->name('bank.ziraatbankSuccess');
//Route::post('/paytest', 'BankController@ziraatbank')->name('bank.paytest');

//  isbankasi
Route::get('/bank/isbankasi', 'BankController@isbankasi')->name('bank.ziraatbankasi');
Route::any('/bank/isbankasi/return', 'BankController@isbankasiReturn')->name('bank.isbankasiSuccess');

// denizbank
Route::get('/bank/denizbank', 'BankController@denizbank')->name('bank.denizbank');
Route::any('/bank/denizbank/return', 'BankController@denizbankReturn')->name('bank.denizbankReturn');

//  vakifbank
Route::get('/bank/vakifbank', 'BankController@vakifbank')->name('bank.vakifbank');
Route::post('/bank/vakifbank', 'BankController@vakifbank')->name('bank.vakifbank');
Route::any('/bank/vakifbank/return', 'BankController@vakifbankGetResponse')->name('bank.vakifbankSuccess');

//  akbank
Route::get('/bank/akbank', 'BankController@akbank')->name('bank.akbank');
Route::any('/bank/akbank/return', 'BankController@akbankReturn')->name('bank.akbankReturn');

Route::get('test', 'Admin\AjaxController@index');

Route::get('test2', 'TestController@index');
Route::get('test3', 'TestController@test3');

Route::get('404', function () {
    return view('404');
})->name('404');

app/ProductType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;

class ProductType extends Model
{

    //Activity Log
    use LogsActivity;
    protected static $logAttributes = [];
    protected static $recordEvents = ['created','updated','deleted'];
    protected $guarded = [];

}

resources/views/admin/product/create.blade.php
@extends('admin.layouts')
@section('content')

@section('breadcrumbs')
    {{ Breadcrumbs::render('product_create') }}
@endsection


<div class="c-body">
    <main class="c-main">
        <div class="container-fluid">
            <div class="fade-in">
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="card mx-2">
                            <div class="card-header"><h4><strong>  {{__('admin/productType.create.product add')}}</strong></h4>
                            </div>
                            <form class="form-horizontal" action="{{route('product.store')}}" id="myform" method="post"
                                  enctype="multipart/form-data">
                                @csrf
                                <div class="card-body">


                                    @if(Session::has('success'))
                                        <div class="alert alert-success" role="alert">
                                            {!! html_entity_decode(Session::get('success')) !!}
                                        </div>
                                    @endif

                                    @if(Session::has('error'))
                                        <div class="alert"> {!! html_entity_decode(Session::get('error')) !!}  </div>
                                    @endif



                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif


                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label"
                                               for="text-input">{{__('admin/productType.create.product type')}}</label>
                                        <div class="col-md-9">
                                            <input class="form-control" id="name" type="text" name="name"
                                                   value="{{ old('name')}}">
                                        </div>
                                    </div>
                                        <div class="form-group row">
                                            <label
                                                class="col-md-3 col-form-label">{{__('admin/productType.create.status')}}</label>
                                            <div class="col-md-9 col-form-label">
                                                <div class="form-check">
                                                    <input class="form-check-input" id="active" type="radio"
                                                           value="active"
                                                           name="status">
                                                    <label class="form-check-label" for="radio1">Aktif</label>
                                                </div>
                                                <div class="form-check">
                                                    <input class="form-check-input" id="passive" type="radio"
                                                           value="passive" name="status">
                                                    <label class="form-check-label" for="radio2">Pasif</label>
                                                </div>

                                            </div>
                                        </div>


                                </div>
                                <div class="card-footer">
                                    <button class="btn btn-primary"
                                            type="submit">{{__('admin/productType.create.save')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-3"></div>

                </div>
            </div>
        </div>
    </main>

</div>-

@endsection
@section('css')@endsection
@section('js')@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts')
@section('content')


@section('breadcrumbs')
    {{ Breadcrumbs::render('product_edit', $products)}}
@endsection



<div class="c-body">
    <main class="c-main">
        <div class="container-fluid">
            <div class="fade-in">

                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="card mx-2">

                            <div class="card-header"><h4><strong> {{__('admin/productType.edit.product edit')}} </strong></h4>
                            </div>
                            <form class="form-horizontal" action="{{route('product.update',$products->id)}}" id="myform"
                                  method="post"
                                  enctype="multipart/form-data">
                                @csrf

                                <div class="card-body">

                                    @method('PUT')
                                    @if(Session::has('success'))
                                        <div class="alert alert-success" role="alert">
                                            {!! html_entity_decode(Session::get('success')) !!}
                                        </div>
                                    @endif

                                    @if(Session::has('error'))
                                        <div class="alert"> {!! html_entity_decode(Session::get('error')) !!}  </div>
                                    @endif



                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif

                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label"
                                               for="text-input">{{__('admin/productType.edit.product type')}}</label>
                                        <div class="col-md-9">
                                            <input class="form-control" id="name" type="text" name="name"
                                                   value="{{$products->name}}">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label
                                            class="col-md-3 col-form-label">{{__('admin/productType.edit.status')}}</label>
                                        <div class="col-md-9 col-form-label">
                                            <div class="form-check">
                                                <input class="form-check-input" id="active" type="radio"
                                                       value="active" <?php if ($products->status == "active") {
                                                    echo "checked";
                                                } ?>
                                                       name="status">
                                                <label class="form-check-label" for="radio1">Aktif</label>
                                            </div>
                                            <div class="form-check">
                                                <input class="form-check-input" id="passive" type="radio"
                                                       value="passive"
                                                       <?php if ($products->status == "passive") {
                                                           echo "checked";
                                                       } ?> name="status">
                                                <label class="form-check-label" for="radio2">Pasif</label>
                                            </div>

                                        </div>
                                    </div>

                                </div>
                                <div class="card-footer">
                                    <button class="btn btn-primary"
                                            type="submit">{{__('admin/productType.edit.update')}}</button>
                                </div>
                            </form>

                        </div>
                    </div>
                    <div class="col-md-3"></div>

                </div>
            </div>
        </div>
    </main>

</div>-


@endsection
@section('css')@endsection
@section('js')@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts')
@section('content')

@section('breadcrumbs')
    {{ Breadcrumbs::render('product') }}
@endsection

@include('components.modal')



<div class="c-body">
    <main class="c-main">
        <div class="container-fluid">
            <div class="fade-in">

                <!-- /.row-->
                <div class="card">

                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            <h4 class="card-title mb-0">
                                {{__('admin/productType.index.product operations')}}</h4>
                            <a class="card-header-action"
                               href="{{route('product.create')}}">
                                <button class="btn btn-success">{{__('admin/productType.create.btn-add')}}</button>
                            </a>

                        </div>
                    </div>

                    <div class="card-body">

                        <table class="table table-responsive-sm table-hover table-outline mb-0">
                            <thead class="thead-light">
                            <tr>
                                <th>#</th>
                                <th>{{__('admin/productType.index.product type')}}</th>
                                <th>{{__('admin/productType.index.status')}}</th>
                                <th></th>
                                <th></th>


                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $product)
                                <tr id="item-{{$product->id}}">
                                    <td> {{$loop->iteration}}    </td>
                                    <td> {{$product->name}}  </td>
                                    <td>
                                        @if($product->status == 'active' )
                                            <span class="badge badge-success">{{__('admin/productType.index.active')}}</span>

                                        @else($product->status =='passive')
                                            <span class="badge badge-danger"> {{__('admin/productType.index.passive')}}</span>

                                        @endif

                                    </td>
                                    <td width="5"><a class="btn btn-warning" role="button"
                                                     href="{{route('product.edit',$product->id)}}">{{__('admin/productType.index.btn-edit')}} </a>

                                    <td width="5">
                                        <button class="btn btn-danger abc" value="{{$product->id}}"
                                                type="button"  data-toggle="modal" data-target="#exampleModal">{{__('admin/user.index.btn-delete')}}</button>
                                    </td>
                                    @endforeach
                                </tr>

                            </tbody>
                        </table>
                        <br>
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-end">
                                {{$data->onEachSide(1)->links()}}
                            </ul>
                        </nav>
                    </div>

                </div>

            </div>
        </div>

    </main>

    <script src="{{asset('assets/js/product.js')}}"></script>

    <script type="text/javascript">
        $(document).ready(function() {

            var data_id = "";

            $(".abc").click(function () {

                data_id = $(this).val();

            });

            $("#continue").click(function () {

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $.ajax({
                    type: 'DELETE',
                    url: '{{getenv('APP_URL')}}' + '/admin/product/' + data_id,

                    success: function (data) {

                        window.location.reload();
                    },
                    error: function (xhr) {

                        alert('Yetki silme işlemi sırasında bir hata meydana geldi.');
                    }
                });
            });
        });
    </script>

@endsection
@section('css')@endsection
@section('js')@endsection