routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Dashboard

Route::get('/', function () {
    return redirect('/admin');
});

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {

        //Ralationship işlemleri için test controller
        Route::get('/test', 'OrganizationController@index');

        Route::get('/', function () {
            return view('admin.default.index');
        })->middleware('auth')->name('default.index');

        //user
        Route::resource('user', 'UserController')->middleware('auth');

        //corporation
        Route::resource('corporation', 'CorporationController')->middleware('auth');
        Route::resource('report', 'ReportController')->middleware('auth');
        Route::get('export', 'ReportController@export');

        Route::get('/ajax/geographic-boundaries', 'AjaxController@getGeographicBoundriesByParentId')->name('ajax.geographic-boundaries');
        Route::get('/ajax/organizations', 'AjaxController@getOrganizationsByParentId')->name('ajax.organizations');
        Route::get('/ajax/corporations', 'AjaxController@getCorporationByOrganizationId')->name('ajax.corporations');
        Route::get('/ajax/roles', 'AjaxController@getRolesByOrganizationId')->name('ajax.roles');
        Route::post('/ajax/enqueue-sms', 'AjaxController@enqueueSms')->name('ajax.enqueue.sms');

        //product type
        Route::resource('product', 'ProductTypeController')->middleware('auth');

        //payment
        Route::resource('payment', 'PaymentController')->middleware('auth');
        Route::put('/payment/cancel/{id}', 'PaymentController@cancelPayment')->name('payment.cancel');

        // Role
        Route::resource('role', 'RoleController')->middleware('auth');

        // Permission
        Route::resource('permission', 'PermissionController')->middleware('auth');

    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-sms', 'SmsController@enqueue');


Route::get('/payment/success', 'PaymentController@success')->name('payments.success');
Route::get('/payment/fail', 'PaymentController@fail')->name('payments.fail');
Route::get('/payment/{code}', 'PaymentController@payment')->name('payments.index');


// finansbank
Route::get('/bank/finansbank', 'BankController@finansbank')->name('bank.finansbank');
Route::any('/bank/finansbank/return', 'BankController@finansbankReturn')->name('bank.finansbankReturn');

//  ziraatbankasi
Route::get('/bank/ziraatbankasi', 'BankController@ziraatbankasi')->name('bank.ziraatbankasi');
Route::any('/bank/ziraatbankasi/return', 'BankController@ziraatbankasiReturn')->name('bank.ziraatbankSuccess');
//Route::post('/paytest', 'BankController@ziraatbank')->name('bank.paytest');

//  isbankasi
Route::get('/bank/isbankasi', 'BankController@isbankasi')->name('bank.ziraatbankasi');
Route::any('/bank/isbankasi/return', 'BankController@isbankasiReturn')->name('bank.isbankasiSuccess');

// denizbank
Route::get('/bank/denizbank', 'BankController@denizbank')->name('bank.denizbank');
Route::any('/bank/denizbank/return', 'BankController@denizbankReturn')->name('bank.denizbankReturn');

//  vakifbank
Route::get('/bank/vakifbank', 'BankController@vakifbank')->name('bank.vakifbank');
Route::post('/bank/vakifbank', 'BankController@vakifbank')->name('bank.vakifbank');
Route::any('/bank/vakifbank/return', 'BankController@vakifbankGetResponse')->name('bank.vakifbankSuccess');

//  akbank
Route::get('/bank/akbank', 'BankController@akbank')->name('bank.akbank');
Route::any('/bank/akbank/return', 'BankController@akbankReturn')->name('bank.akbankReturn');

Route::get('test', 'Admin\AjaxController@index');

Route::get('test2', 'TestController@index');
Route::get('test3', 'TestController@test3');

Route::get('404', function () {
    return view('404');
})->name('404');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App;
use App\Organization;
use App\Http\Requests\EditUserRequest;
use App\OrganizationType;
use Spatie\Permission\Models\Role;
use App\Http\Requests\StoreUserPost;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if ( !Auth::user()->can('user operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $data = User::paginate(10);
        $skipped = ($data->currentPage() * $data->perPage()) - $data->perPage();
        return view('admin.users.index')->with(compact('data', 'skipped'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if ( !Auth::user()->can('user operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $organizationTypes = OrganizationType::all();

        return view('admin.users.create', compact('organizationTypes'));
    }

    /**
     * @param StoreUserPost $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Throwable
     */
    public function store(StoreUserPost $request)
    {
        if ( !Auth::user()->can('user operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $role = Role::findByName($request->role);

        throw_if($request->organization_type != $role->organization_type_id, App\Exceptions\RoleOrganizationTypeMismatchException::class);

        if (Auth::user()->roles()->first()->name != 'Admin' && $request->role == 'Admin') {

            throw new App\Exceptions\AdminRoleCreationException("Yetkisiz işlem.");
        }

        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->corporation_id = 1;
        $user->save();

        if ($user) {

            switch ($request->organization_type) {

                case 1:
                    $user->assignRole($request->organization_type, $request->role);
                    break;
                case 2:
                    $user->assignRole($request->region, $request->role);
                    break;
                case 3:
                    $user->assignRole($request->zone, $request->role);
                    break;
                case 4:
                    $user->assignRole($request->corporation, $request->role);
                    break;
            }

            return redirect(route('user.index'))->with('success', 'işlem başarılı');
        }

        return back()->with('error', 'İşlem Başarısız');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if ( Auth::user()->id != $id && !Auth::user()->can('user operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $user = User::where('id', $id)->first();

        if ($user->roles()->first()->name == 'Admin' && Auth::user()->roles()->first()->name != 'Admin') {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $organizationTypes = OrganizationType::all();
        $roles = Role::all();

        $organizationId = DB::table('model_has_roles')
            ->where([
                'role_id' => $user->roles()->first()->id,
                'model_id' => $user->id
            ])
            ->first()
            ->organization_id;

        $organizationTypeId = $user->roles()->first()->organization_type_id;
        $role_id = Auth::user()->roles()->first()->id;

        $regions = $zones = $corporations = [];

        switch ($organizationTypeId) {

            case 1:

                if ($role_id != 1)//kullanıcı çamlıca muhasebe ise rol inputuna sadece çamlıca muhasebe gelsin
                {
                    $rolesOrganizationsTypes = Role::where('organization_type_id', $organizationTypeId)->where('id','!=',1)->get();
                }
                else
                {
                    $rolesOrganizationsTypes = Role::where('organization_type_id', $organizationTypeId)->get();
                }

                $merkez = Organization::find(1);

                $organizationRegion = Organization::where('id', $organizationId)->first();

                return view('admin.users.edit', compact(
                    'user',
                    'organizationTypes',
                    'roles',
                    'rolesOrganizationsTypes',
                    'zones',
                    'corporations',
                    'organizationRegion',
                    'regions',
                    'merkez',
                    'organizationId'
                ));
            case 2:
                $rolesOrganizationsTypes = Role::where('organization_type_id', $organizationTypeId)->get();

                $organizationRegion = Organization::where('id', $organizationId)->first();
                $regions = Organization::where('parent_id', $organizationRegion->parent_id)->get();
                $merkez = Organization::find(1);

                return view('admin.users.edit', compact(
                    'user',
                    'organizationTypes',
                    'roles',
                    'rolesOrganizationsTypes',
                    'zones',
                    'corporations',
                    'organizationRegion',
                    'regions',
                    'merkez',
                    'organizationId'
                ));
            case 3:
                $rolesOrganizationsTypes = Role::where('organization_type_id', $organizationTypeId)->get();

                $organizationZone = Organization::where('id', $organizationId)->first();
                $zones = Organization::where('parent_id', $organizationZone->parent_id)->get();
                $organizationRegion = Organization::where('id', $organizationZone->parent_id)->first();
                $regions = Organization::where('parent_id', $organizationRegion->parent_id)->get();
                $merkez = Organization::find(1);

                return view('admin.users.edit', compact(
                    'user',
                    'organizationTypes',
                    'roles',
                    'rolesOrganizationsTypes',
                    'organizationZone',
                    'zones',
                    'corporations',
                    'organizationRegion',
                    'regions',
                    'merkez',
                    'organizationId'
                ));

            case 4:
                $rolesOrganizationsTypes = Role::where('organization_type_id', $organizationTypeId)->get();
                $corporation = Organization::where('id', $organizationId)->first();
                $corporations = Organization::where('parent_id', $corporation->parent_id)->get();
                $organizationZone = $corporation->parent;
                $zones = Organization::where('parent_id', $organizationZone->parent_id)->get();
                $organizationRegion = Organization::where('id', $organizationZone->parent_id)->first();
                $regions = Organization::where('parent_id', $organizationRegion->parent_id)->get();
                $merkez = Organization::find(1);

                return view('admin.users.edit', compact(
                    'user',
                    'organizationTypes',
                    'roles',
                    'rolesOrganizationsTypes',
                    'corporation',
                    'corporations',
                    'organizationZone',
                    'zones',
                    'organizationRegion',
                    'regions',
                    'merkez',
                    'organizationId'
                ));
        }

        return view('admin.users.edit', compact('user', 'organizationTypes', 'roles', 'organizationId'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditUserRequest $request, $id)
    {
        if ( Auth::user()->id != $id && !Auth::user()->can('user operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        if (Auth::user()->roles()->first()->name != 'Admin' && $request->role == 'Admin') {

            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }
        if (Auth::user()->roles()->first()->name != 'Admin' &&  $request->role == 1) {

            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $user = User::find($id);

        if ($user->roles()->first()->name == 'Admin' && Auth::user()->roles()->first()->name != 'Admin') {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        if (!empty($request->password)) {

            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = Hash::make($request->password);
            $user->save();
        } else {

            $user->name = $request->name;
            $user->email = $request->email;
            $user->save();
        }

        if (!$user) {

            return back()->with('error', 'İşlem Başarısız');
        }

resources/views/admin/users/index.blade.php
@extends('admin.layouts')
@section('content')

@section('breadcrumbs')
    {{ Breadcrumbs::render('user') }}
@endsection

@include('components.modal')

<div class="c-body">
    <main class="c-main">
        <div class="container-fluid">
            <div class="fade-in">
                <!-- /.row-->
                <div class="card">

                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            <h4 class="card-title mb-0">
                                {{__('admin/user.index.user operations')}}
                            </h4>
                            <a class="card-header-action"
                               href="{{route('user.create')}}">
                                <button class="btn btn-success">{{__('admin/user.index.btn-add')}}</button>
                            </a>
                        </div>
                    </div>

                    <div class="card-body">
                        <table class="table table-responsive-sm table-hover table-outline mb-0">
                            <thead class="thead-light">
                            <tr>
                                <th>#</th>
                                <th>{{__('admin/user.index.name')}}</th>
                                <th>{{__('admin/user.index.email')}}</th>
                                <th>{{__('admin/user.index.organization')}}</th>
                                <th>{{__('admin/user.index.role')}}</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $user)
                                <tr id="item-{{$user->id}}">
                                    <td> {{$loop->iteration + $skipped}} </td>
                                    <td> {{$user->name}}  </td>
                                    <td> {{$user->email}} </td>
                                    <td>  {{$user->getOrganizationHierarchy()['description']}} </td>
                                    <td> {{$user->roles()->first()->name}} </td>
                                    <td width="5"><a class="btn btn-warning" role="button"
                                                     href="{{route('user.edit',$user->id)}}">{{__('admin/user.index.btn-edit')}} </a>
                                    <td width="5">

                                        <button class="btn btn-danger abc" value="{{$user->id}}"
                                                type="button"  data-toggle="modal" data-target="#exampleModal">{{__('admin/user.index.btn-delete')}}</button>

                                    </td>
                                    @endforeach
                                </tr>
                            </tbody>
                        </table>
                        <br>
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-end">
                                {{$data->onEachSide(1)->links()}}
                            </ul>
                        </nav>
                    </div>

                </div>

            </div>
        </div>

    </main>
    <script src="{{asset('assets/js/user.js')}}"></script>
    <script type="text/javascript">
        $(document).ready(function() {

            var data_id = "";

            $(".abc").click(function () {

                data_id = $(this).val();

            });

            $("#continue").click(function () {

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });

                $.ajax({
                    type: 'DELETE',
                    url: '{{getenv('APP_URL')}}' + '/admin/user/' + data_id,

                    success: function (data) {

                        window.location.reload();
                    },
                    error: function (xhr) {

                        alert('Yetki silme işlemi sırasında bir hata meydana geldi.');
                    }
                });
            });
        });
    </script>
@endsection
@section('css')@endsection
@section('js')@endsection