routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Dashboard

Route::get('/', function () {
    return redirect('/admin');
});

Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {

        //Ralationship işlemleri için test controller
        Route::get('/test', 'OrganizationController@index');

        Route::get('/', function () {
            return view('admin.default.index');
        })->middleware('auth')->name('default.index');

        //user
        Route::resource('user', 'UserController')->middleware('auth');

        //corporation
        Route::resource('corporation', 'CorporationController')->middleware('auth');
        Route::resource('report', 'ReportController')->middleware('auth');
        Route::get('export', 'ReportController@export');

        Route::get('/ajax/geographic-boundaries', 'AjaxController@getGeographicBoundriesByParentId')->name('ajax.geographic-boundaries');
        Route::get('/ajax/organizations', 'AjaxController@getOrganizationsByParentId')->name('ajax.organizations');
        Route::get('/ajax/corporations', 'AjaxController@getCorporationByOrganizationId')->name('ajax.corporations');
        Route::get('/ajax/roles', 'AjaxController@getRolesByOrganizationId')->name('ajax.roles');
        Route::post('/ajax/enqueue-sms', 'AjaxController@enqueueSms')->name('ajax.enqueue.sms');

        //product type
        Route::resource('product', 'ProductTypeController')->middleware('auth');

        //payment
        Route::resource('payment', 'PaymentController')->middleware('auth');
        Route::put('/payment/cancel/{id}', 'PaymentController@cancelPayment')->name('payment.cancel');

        // Role
        Route::resource('role', 'RoleController')->middleware('auth');

        // Permission
        Route::resource('permission', 'PermissionController')->middleware('auth');

    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('test-sms', 'SmsController@enqueue');


Route::get('/payment/success', 'PaymentController@success')->name('payments.success');
Route::get('/payment/fail', 'PaymentController@fail')->name('payments.fail');
Route::get('/payment/{code}', 'PaymentController@payment')->name('payments.index');


// finansbank
Route::get('/bank/finansbank', 'BankController@finansbank')->name('bank.finansbank');
Route::any('/bank/finansbank/return', 'BankController@finansbankReturn')->name('bank.finansbankReturn');

//  ziraatbankasi
Route::get('/bank/ziraatbankasi', 'BankController@ziraatbankasi')->name('bank.ziraatbankasi');
Route::any('/bank/ziraatbankasi/return', 'BankController@ziraatbankasiReturn')->name('bank.ziraatbankSuccess');
//Route::post('/paytest', 'BankController@ziraatbank')->name('bank.paytest');

//  isbankasi
Route::get('/bank/isbankasi', 'BankController@isbankasi')->name('bank.ziraatbankasi');
Route::any('/bank/isbankasi/return', 'BankController@isbankasiReturn')->name('bank.isbankasiSuccess');

// denizbank
Route::get('/bank/denizbank', 'BankController@denizbank')->name('bank.denizbank');
Route::any('/bank/denizbank/return', 'BankController@denizbankReturn')->name('bank.denizbankReturn');

//  vakifbank
Route::get('/bank/vakifbank', 'BankController@vakifbank')->name('bank.vakifbank');
Route::post('/bank/vakifbank', 'BankController@vakifbank')->name('bank.vakifbank');
Route::any('/bank/vakifbank/return', 'BankController@vakifbankGetResponse')->name('bank.vakifbankSuccess');

//  akbank
Route::get('/bank/akbank', 'BankController@akbank')->name('bank.akbank');
Route::any('/bank/akbank/return', 'BankController@akbankReturn')->name('bank.akbankReturn');

Route::get('test', 'Admin\AjaxController@index');

Route::get('test2', 'TestController@index');
Route::get('test3', 'TestController@test3');

Route::get('404', function () {
    return view('404');
})->name('404');

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\EditPermissionPost;
use App\Http\Requests\StorePermissionPost;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        if ( !Auth::user()->can('permission operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $permissions = Permission::paginate(20);
        $skipped = ($permissions->currentPage() * $permissions->perPage()) - $permissions->perPage();

        return view('admin.permission.index')->with(compact('permissions','skipped'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        if ( !Auth::user()->can('permission operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        return view('admin.permission.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StorePermissionPost $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(StorePermissionPost $request)
    {
        if ( !Auth::user()->can('permission operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $permission = Permission::create([
            'name' => $request->permission
        ]);

        if($permission){

            activity()
                ->performedOn($permission)
                ->causedBy(auth()->user())
                ->log('created');

            return redirect(route('permission.index'))->with('success','İşlem başarılı.');
        }

        return back()->with('error','İşlem Başarısız.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        if ( !Auth::user()->can('permission operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $permission = Permission::findById($id);

        return view('admin.permission.edit')->with('permission',$permission);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EditPermissionPost $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(EditPermissionPost $request, $id)
    {
        if ( !Auth::user()->can('permission operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $permission = Permission::findById($id);

        $permission->name = $request->permission;
        $permission->save();

        if ($permission) {

            //activity log
            $modal = Permission::where('id', $id)->first();
            activity()
                ->performedOn($modal)
                ->causedBy(auth()->user())
                ->log('updated');

            return back()->with('success', 'İşlem Başarılı');
        }

        return back()->with('error', 'İşlem Başarısız');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        if ( !Auth::user()->can('permission operations') ) {
            return abort(403, 'Yetkiniz bulunmamaktadır!');
        }

        $permission = Permission::findById($id);

        if ($permission->delete()) {

            activity()
                ->performedOn($permission)
                ->causedBy(auth()->user())
                ->log('deleted');

            return true;
        }

        return false;
    }
}

resources/views/admin/permission/create.blade.php
@extends('admin.layouts')
@section('content')

@section('breadcrumbs')
    {{ Breadcrumbs::render('permission_create') }}
@endsection

<div class="c-body">
    <main class="c-main">
        <div class="container-fluid">
            <div class="fade-in">
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="card mx-2">
                            <div class="card-header"><h4><strong>  {{__('admin/user.create.permission add')}}</strong></h4>
                            </div>
                            <form class="form-horizontal" action="{{route('permission.store')}}" id="myform" method="post"
                                  enctype="multipart/form-data">
                                @csrf
                                <div class="card-body">

                                    @if(Session::has('success'))
                                        <div class="success"> {!! html_entity_decode(Session::get('success')) !!} </div>
                                    @endif

                                    @if(Session::has('error'))
                                        <div class="alert"> {!! html_entity_decode(Session::get('error')) !!}  </div>
                                    @endif

                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif

                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label"
                                               for="text-input">{{__('admin/user.create.permission')}}</label>
                                        <div class="col-md-9">
                                            <input class="form-control" id="permission" type="text" name="permission"
                                                   value="{{ old('permission')}}">
                                        </div>
                                    </div>

                                </div>
                                <div class="card-footer">
                                    <button class="btn btn-primary"
                                            type="submit">{{__('admin/user.create.save')}}</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </div>
        </div>
    </main>

</div>-

@endsection
@section('css')@endsection
@section('js')@endsection

resources/views/admin/permission/edit.blade.php
@extends('admin.layouts')
@section('content')

@section('breadcrumbs')
    {{ Breadcrumbs::render('permission_edit', $permission)}}
@endsection

<div class="c-body">
    <main class="c-main">
        <div class="container-fluid">
            <div class="fade-in">

                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6">
                        <div class="card mx-2">

                            <div class="card-header"><h4><strong> {{__('admin/user.edit.permission edit')}} </strong></h4>
                            </div>
                            <form class="form-horizontal" action="{{route('permission.update',$permission->id)}}" id="myform"
                                  method="post"
                                  enctype="multipart/form-data">
                                @csrf

                                <div class="card-body">

                                    @method('PUT')
                                    @if(Session::has('success'))
                                        <div
                                            class="alert-success"> {!! html_entity_decode(Session::get('success')) !!} </div>
                                    @endif

                                    @if(Session::has('error'))
                                        <div class="alert"> {!! html_entity_decode(Session::get('error')) !!}  </div>
                                    @endif

                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif

                                    <div class="form-group row">
                                        <label class="col-md-3 col-form-label"
                                               for="text-input">{{__('admin/user.edit.permission')}}</label>
                                        <div class="col-md-9">
                                            <input class="form-control" id="permission" type="text" name="permission"
                                                   value="{{$permission->name}}">
                                        </div>
                                    </div>

                                </div>
                                <div class="card-footer">
                                    <button class="btn btn-primary"
                                            type="submit">{{__('admin/user.edit.update')}}</button>
                                </div>
                            </form>

                        </div>
                    </div>
                    <div class="col-md-3"></div>

                </div>
            </div>
        </div>
    </main>

</div>

@endsection
@section('css')@endsection
@section('js')@endsection

resources/views/admin/permission/index.blade.php
@extends('admin.layouts')
@section('content')

@section('breadcrumbs')
    {{ Breadcrumbs::render('permission') }}
@endsection

@include('components.permission.deletemodal')

<div class="c-body">
    <main class="c-main">
        <div class="container-fluid">
            <div class="fade-in">
                <!-- /.row-->
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between">
                            <h4 class="card-title mb-0">
                                {{__('admin/user.index.permissions')}}
                            </h4>
                            <a class="card-header-action"
                               href="{{route('permission.create')}}">
                                <button class="btn btn-success">{{__('admin/user.index.btn-add')}}</button>
                            </a>
                        </div>
                    </div>

                    <div class="card-body">
                        <table class="table table-responsive-sm table-hover table-outline mb-0">
                            <thead class="thead-light">
                            <tr>
                                <th>#</th>
                                <th>{{__('admin/user.index.permission')}}</th>
                                <th>{{__('admin/user.index.created_at')}}</th>
                                <th>{{__('admin/user.index.updated_at')}}</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($permissions as $permission)

                                <tr id="item-{{$permission->id}}">
                                    <td> {{$loop->iteration + $skipped}} </td>
                                    <td> {{$permission->name}}  </td>
                                    <td> {{$permission->created_at}} </td>
                                    <td> {{$permission->updated_at}} </td>
                                    <td width="5"><a class="btn btn-warning" role="button"
                                                     href="{{route('permission.edit',$permission->id)}}">{{__('admin/user.index.btn-edit')}} </a>
                                    <td width="5">
                                        <button class="btn btn-danger permissionDelete" value="{{$permission->id}}"
                                                type="button"  data-toggle="modal" data-target="#deleteModal">{{__('admin/user.index.btn-delete')}}</button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </main>

    <script src="{{asset('assets/js/permission.js')}}"></script>

@endsection
@section('css')@endsection
@section('js')@endsection